services:
  jenkins:
    build: .
    container_name: jenkins
    restart: on-failure
    privileged: true
    user: root
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - 9999:8080
      - 50000:50000
